# Generated by Django 2.2.1 on 2019-05-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctgov_group_code', models.CharField(blank=True, max_length=255, null=True)),
                ('units', models.CharField(blank=True, max_length=255, null=True)),
                ('scope', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'baseline_counts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaselineMeasurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctgov_group_code', models.CharField(blank=True, max_length=255, null=True)),
                ('classification', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('units', models.CharField(blank=True, max_length=255, null=True)),
                ('param_type', models.CharField(blank=True, max_length=255, null=True)),
                ('param_value', models.CharField(blank=True, max_length=255, null=True)),
                ('param_value_num', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('dispersion_type', models.CharField(blank=True, max_length=255, null=True)),
                ('dispersion_value', models.CharField(blank=True, max_length=255, null=True)),
                ('dispersion_value_num', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('dispersion_lower_limit', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('dispersion_upper_limit', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('explanation_of_na', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'baseline_measurements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BriefSummaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'brief_summaries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BrowseConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesh_term', models.CharField(blank=True, max_length=255, null=True)),
                ('downcase_mesh_term', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'browse_conditions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BrowseInterventions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesh_term', models.CharField(blank=True, max_length=255, null=True)),
                ('downcase_mesh_term', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'browse_interventions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalculatedValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_facilities', models.IntegerField(blank=True, null=True)),
                ('number_of_nsae_subjects', models.IntegerField(blank=True, null=True)),
                ('number_of_sae_subjects', models.IntegerField(blank=True, null=True)),
                ('registered_in_calendar_year', models.IntegerField(blank=True, null=True)),
                ('nlm_download_date', models.DateField(blank=True, null=True)),
                ('actual_duration', models.IntegerField(blank=True, null=True)),
                ('were_results_reported', models.BooleanField(blank=True, null=True)),
                ('months_to_report_results', models.IntegerField(blank=True, null=True)),
                ('has_us_facility', models.BooleanField(blank=True, null=True)),
                ('has_single_facility', models.BooleanField(blank=True, null=True)),
                ('minimum_age_num', models.IntegerField(blank=True, null=True)),
                ('maximum_age_num', models.IntegerField(blank=True, null=True)),
                ('minimum_age_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('maximum_age_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_primary_outcomes_to_measure', models.IntegerField(blank=True, null=True)),
                ('number_of_secondary_outcomes_to_measure', models.IntegerField(blank=True, null=True)),
                ('number_of_other_outcomes_to_measure', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calculated_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CentralContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'central_contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('downcase_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'conditions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('removed', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DesignGroupInterventions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'design_group_interventions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DesignGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'design_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DesignOutcomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_type', models.CharField(blank=True, max_length=255, null=True)),
                ('measure', models.TextField(blank=True, null=True)),
                ('time_frame', models.TextField(blank=True, null=True)),
                ('population', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'design_outcomes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Designs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.CharField(blank=True, max_length=255, null=True)),
                ('intervention_model', models.CharField(blank=True, max_length=255, null=True)),
                ('observational_model', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('time_perspective', models.CharField(blank=True, max_length=255, null=True)),
                ('masking', models.CharField(blank=True, max_length=255, null=True)),
                ('masking_description', models.TextField(blank=True, null=True)),
                ('intervention_model_description', models.TextField(blank=True, null=True)),
                ('subject_masked', models.BooleanField(blank=True, null=True)),
                ('caregiver_masked', models.BooleanField(blank=True, null=True)),
                ('investigator_masked', models.BooleanField(blank=True, null=True)),
                ('outcomes_assessor_masked', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'designs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailedDescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detailed_descriptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(blank=True, max_length=255, null=True)),
                ('document_type', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DropWithdrawals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctgov_group_code', models.CharField(blank=True, max_length=255, null=True)),
                ('period', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'drop_withdrawals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eligibilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampling_method', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('minimum_age', models.CharField(blank=True, max_length=255, null=True)),
                ('maximum_age', models.CharField(blank=True, max_length=255, null=True)),
                ('healthy_volunteers', models.CharField(blank=True, max_length=255, null=True)),
                ('population', models.TextField(blank=True, null=True)),
                ('criteria', models.TextField(blank=True, null=True)),
                ('gender_description', models.TextField(blank=True, null=True)),
                ('gender_based', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eligibilities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'facilities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacilityContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'facility_contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacilityInvestigators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'facility_investigators',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IdInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(blank=True, max_length=255, null=True)),
                ('id_value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'id_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InterventionOtherNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'intervention_other_names',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interventions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_type', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'interventions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IpdInformationTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ipd_information_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('downcase_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'keywords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeshHeadings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifier', models.CharField(blank=True, max_length=255, null=True)),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'mesh_headings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeshTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifier', models.CharField(blank=True, max_length=255, null=True)),
                ('tree_number', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('mesh_term', models.CharField(blank=True, max_length=255, null=True)),
                ('downcase_mesh_term', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'mesh_terms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Milestones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctgov_group_code', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('period', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'milestones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OutcomeAnalyses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_inferiority_type', models.CharField(blank=True, max_length=255, null=True)),
                ('non_inferiority_description', models.TextField(blank=True, null=True)),
                ('param_type', models.CharField(blank=True, max_length=255, null=True)),
                ('param_value', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('dispersion_type', models.CharField(blank=True, max_length=255, null=True)),
                ('dispersion_value', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('p_value_modifier', models.CharField(blank=True, max_length=255, null=True)),
                ('p_value', models.FloatField(blank=True, null=True)),
                ('ci_n_sides', models.CharField(blank=True, max_length=255, null=True)),
                ('ci_percent', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('ci_lower_limit', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('ci_upper_limit', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('ci_upper_limit_na_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('p_value_description', models.CharField(blank=True, max_length=255, null=True)),
                ('method', models.CharField(blank=True, max_length=255, null=True)),
                ('method_description', models.TextField(blank=True, null=True)),
                ('estimate_description', models.TextField(blank=True, null=True)),
                ('groups_description', models.TextField(blank=True, null=True)),
                ('other_analysis_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'outcome_analyses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OutcomeAnalysisGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctgov_group_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'outcome_analysis_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OutcomeCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctgov_group_code', models.CharField(blank=True, max_length=255, null=True)),
                ('scope', models.CharField(blank=True, max_length=255, null=True)),
                ('units', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'outcome_counts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OutcomeMeasurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctgov_group_code', models.CharField(blank=True, max_length=255, null=True)),
                ('classification', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('units', models.CharField(blank=True, max_length=255, null=True)),
                ('param_type', models.CharField(blank=True, max_length=255, null=True)),
                ('param_value', models.CharField(blank=True, max_length=255, null=True)),
                ('param_value_num', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('dispersion_type', models.CharField(blank=True, max_length=255, null=True)),
                ('dispersion_value', models.CharField(blank=True, max_length=255, null=True)),
                ('dispersion_value_num', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('dispersion_lower_limit', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('dispersion_upper_limit', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('explanation_of_na', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'outcome_measurements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Outcomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_type', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_frame', models.TextField(blank=True, null=True)),
                ('population', models.TextField(blank=True, null=True)),
                ('anticipated_posting_date', models.DateField(blank=True, null=True)),
                ('anticipated_posting_month_year', models.CharField(blank=True, max_length=255, null=True)),
                ('units', models.CharField(blank=True, max_length=255, null=True)),
                ('units_analyzed', models.CharField(blank=True, max_length=255, null=True)),
                ('dispersion_type', models.CharField(blank=True, max_length=255, null=True)),
                ('param_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'outcomes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OverallOfficials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'overall_officials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipantFlows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruitment_details', models.TextField(blank=True, null=True)),
                ('pre_assignment_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'participant_flows',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PendingResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, max_length=255, null=True)),
                ('event_date_description', models.CharField(blank=True, max_length=255, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pending_results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProvidedDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, max_length=255, null=True)),
                ('has_protocol', models.BooleanField(blank=True, null=True)),
                ('has_icf', models.BooleanField(blank=True, null=True)),
                ('has_sap', models.BooleanField(blank=True, null=True)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'provided_documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportedEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctgov_group_code', models.CharField(blank=True, max_length=255, null=True)),
                ('time_frame', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, max_length=255, null=True)),
                ('default_vocab', models.CharField(blank=True, max_length=255, null=True)),
                ('default_assessment', models.CharField(blank=True, max_length=255, null=True)),
                ('subjects_affected', models.IntegerField(blank=True, null=True)),
                ('subjects_at_risk', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_count', models.IntegerField(blank=True, null=True)),
                ('organ_system', models.CharField(blank=True, max_length=255, null=True)),
                ('adverse_event_term', models.CharField(blank=True, max_length=255, null=True)),
                ('frequency_threshold', models.IntegerField(blank=True, null=True)),
                ('vocab', models.CharField(blank=True, max_length=255, null=True)),
                ('assessment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'reported_events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResponsibleParties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_party_type', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'responsible_parties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultAgreements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi_employee', models.CharField(blank=True, max_length=255, null=True)),
                ('agreement', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'result_agreements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'result_contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctgov_group_code', models.CharField(blank=True, max_length=255, null=True)),
                ('result_type', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'result_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_class', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_or_collaborator', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sponsors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nct_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('nlm_download_date_description', models.CharField(blank=True, max_length=255, null=True)),
                ('study_first_submitted_date', models.DateField(blank=True, null=True)),
                ('results_first_submitted_date', models.DateField(blank=True, null=True)),
                ('disposition_first_submitted_date', models.DateField(blank=True, null=True)),
                ('last_update_submitted_date', models.DateField(blank=True, null=True)),
                ('study_first_submitted_qc_date', models.DateField(blank=True, null=True)),
                ('study_first_posted_date', models.DateField(blank=True, null=True)),
                ('study_first_posted_date_type', models.CharField(blank=True, max_length=255, null=True)),
                ('results_first_submitted_qc_date', models.DateField(blank=True, null=True)),
                ('results_first_posted_date', models.DateField(blank=True, null=True)),
                ('results_first_posted_date_type', models.CharField(blank=True, max_length=255, null=True)),
                ('disposition_first_submitted_qc_date', models.DateField(blank=True, null=True)),
                ('disposition_first_posted_date', models.DateField(blank=True, null=True)),
                ('disposition_first_posted_date_type', models.CharField(blank=True, max_length=255, null=True)),
                ('last_update_submitted_qc_date', models.DateField(blank=True, null=True)),
                ('last_update_posted_date', models.DateField(blank=True, null=True)),
                ('last_update_posted_date_type', models.CharField(blank=True, max_length=255, null=True)),
                ('start_month_year', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date_type', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('verification_month_year', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('completion_month_year', models.CharField(blank=True, max_length=255, null=True)),
                ('completion_date_type', models.CharField(blank=True, max_length=255, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('primary_completion_month_year', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_completion_date_type', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_completion_date', models.DateField(blank=True, null=True)),
                ('target_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('study_type', models.CharField(blank=True, max_length=255, null=True)),
                ('acronym', models.CharField(blank=True, max_length=255, null=True)),
                ('baseline_population', models.TextField(blank=True, null=True)),
                ('brief_title', models.TextField(blank=True, null=True)),
                ('official_title', models.TextField(blank=True, null=True)),
                ('overall_status', models.CharField(blank=True, max_length=255, null=True)),
                ('last_known_status', models.CharField(blank=True, max_length=255, null=True)),
                ('phase', models.CharField(blank=True, max_length=255, null=True)),
                ('enrollment', models.IntegerField(blank=True, null=True)),
                ('enrollment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('limitations_and_caveats', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_arms', models.IntegerField(blank=True, null=True)),
                ('number_of_groups', models.IntegerField(blank=True, null=True)),
                ('why_stopped', models.CharField(blank=True, max_length=255, null=True)),
                ('has_expanded_access', models.BooleanField(blank=True, null=True)),
                ('expanded_access_type_individual', models.BooleanField(blank=True, null=True)),
                ('expanded_access_type_intermediate', models.BooleanField(blank=True, null=True)),
                ('expanded_access_type_treatment', models.BooleanField(blank=True, null=True)),
                ('has_dmc', models.BooleanField(blank=True, null=True)),
                ('is_fda_regulated_drug', models.BooleanField(blank=True, null=True)),
                ('is_fda_regulated_device', models.BooleanField(blank=True, null=True)),
                ('is_unapproved_device', models.BooleanField(blank=True, null=True)),
                ('is_ppsd', models.BooleanField(blank=True, null=True)),
                ('is_us_export', models.BooleanField(blank=True, null=True)),
                ('biospec_retention', models.CharField(blank=True, max_length=255, null=True)),
                ('biospec_description', models.TextField(blank=True, null=True)),
                ('ipd_time_frame', models.CharField(blank=True, max_length=255, null=True)),
                ('ipd_access_criteria', models.CharField(blank=True, max_length=255, null=True)),
                ('ipd_url', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_to_share_ipd', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_to_share_ipd_description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'studies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudyReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=255, null=True)),
                ('citation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'study_references',
                'managed': False,
            },
        ),
    ]
